### ISSUE TITLE
Can we operate ops manager through this library?

### ISSUE THREAD

**Issue by shuchangbruce** [cloudfoundry-incubator/uaa-java-client#6]
Hi there, a question regarding ops manager.
In command line I use
$ uaac target https://*****.org/uaa --skip-ssl-validation
$ uaac token owner get
$ uaac curl -k https://****.org/api/v0/diagnostic_report
.......
to check and operate ops manager.

Now I'm thinking an automation tool to automatically check and update my products on ops manager. I'm using java and I figure this library may do the work. Does this library offer such functions? If not, how could I reach my goal?

Thank you so much.

**Comment by jghiloni** [comment]
It _would_ work, but I'm not sure it's the best idea. The new version of the [CF Java Client](https://github.com/cloudfoundry/cf-java-client) has a reactive `UaaClient` class that is more supported. You should probably use that.
